"""add created_at to all entities

Revision ID: 3dc73576763e
Revises: b3c4d5e6f7a8
Create Date: 2026-05-13 18:34:07.477520

"""

# ruff: noqa
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.mysql import DATETIME


revision: str = "3dc73576763e"
down_revision: Union[str, None] = "b3c4d5e6f7a8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accounts",
        sa.Column(
            "created_at",
            DATETIME(fsp=6),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "incidents",
        sa.Column(
            "created_at",
            DATETIME(fsp=6),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "invite_tokens",
        sa.Column(
            "created_at",
            DATETIME(fsp=6),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "locations",
        sa.Column(
            "created_at",
            DATETIME(fsp=6),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "parties",
        sa.Column(
            "created_at",
            DATETIME(fsp=6),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "police",
        sa.Column(
            "created_at",
            DATETIME(fsp=6),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "students",
        sa.Column(
            "created_at",
            DATETIME(fsp=6),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("students", "created_at")
    op.drop_column("police", "created_at")
    op.drop_column("parties", "created_at")
    op.drop_column("locations", "created_at")
    op.drop_column("invite_tokens", "created_at")
    op.drop_column("incidents", "created_at")
    op.drop_column("accounts", "created_at")
    # ### end Alembic commands ###
