"""add_email_unsubscribes

Revision ID: 6315f52c93cf
Revises: 3dc73576763e
Create Date: 2026-05-28 20:04:26.123313

"""

# ruff: noqa
from typing import Sequence, Union

import src.core.types
from alembic import op
import sqlalchemy as sa


revision: str = "6315f52c93cf"
down_revision: Union[str, None] = "3dc73576763e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_unsubscribes",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            src.core.types.UTCDateTime(fsp=6),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("email"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("email_unsubscribes")
    # ### end Alembic commands ###
