"""add_password_reset_token_to_police

Revision ID: 657666028e23
Revises: 123806024a92
Create Date: 2026-06-17 14:51:36.379449

"""

# ruff: noqa
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src.core.types


revision: str = "657666028e23"
down_revision: Union[str, None] = "123806024a92"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("police", sa.Column("password_reset_token", sa.String(length=255), nullable=True))
    op.add_column(
        "police",
        sa.Column(
            "password_reset_token_expires_at", src.core.types.UTCDateTime(fsp=6), nullable=True
        ),
    )
    op.create_check_constraint(
        "ck_police_password_reset_token_both_null_or_set",
        "police",
        "(password_reset_token IS NULL AND password_reset_token_expires_at IS NULL)"
        " OR (password_reset_token IS NOT NULL AND password_reset_token_expires_at IS NOT NULL)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_police_password_reset_token_both_null_or_set", "police", type_="check")
    op.drop_column("police", "password_reset_token_expires_at")
    op.drop_column("police", "password_reset_token")
    # ### end Alembic commands ###
