"""initial setup

Revision ID: f18af3b77940
Revises:
Create Date: 2026-04-21 14:58:58.873685

"""

# ruff: noqa
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

revision: str = "f18af3b77940"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("first_name", sa.String(length=255), nullable=False),
        sa.Column("last_name", sa.String(length=255), nullable=False),
        sa.Column("pid", sa.String(length=9), nullable=False),
        sa.Column("onyen", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum("STUDENT", "STAFF", "ADMIN", name="accountrole", native_enum=False, length=20),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_accounts_email"), "accounts", ["email"], unique=True)
    op.create_index(op.f("ix_accounts_onyen"), "accounts", ["onyen"], unique=True)
    op.create_index(op.f("ix_accounts_pid"), "accounts", ["pid"], unique=True)
    op.create_table(
        "locations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("google_place_id", sa.String(length=255), nullable=False),
        sa.Column("formatted_address", sa.String(length=500), nullable=False),
        sa.Column("latitude", sa.DECIMAL(precision=10, scale=8), nullable=False),
        sa.Column("longitude", sa.DECIMAL(precision=11, scale=8), nullable=False),
        sa.Column("hold_expiration", mssql.DATETIMEOFFSET(), nullable=True),
        sa.Column("street_number", sa.String(length=20), nullable=True),
        sa.Column("street_name", sa.String(length=255), nullable=True),
        sa.Column("unit", sa.String(length=50), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("county", sa.String(length=100), nullable=True),
        sa.Column("state", sa.String(length=50), nullable=True),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.Column("zip_code", sa.String(length=10), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_lat_lng", "locations", ["latitude", "longitude"], unique=False)
    op.create_index(
        op.f("ix_locations_google_place_id"), "locations", ["google_place_id"], unique=True
    )
    op.create_table(
        "police",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum("OFFICER", "POLICE_ADMIN", name="policerole", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("is_verified", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("verification_token", sa.String(), nullable=True),
        sa.Column("verification_token_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(verification_token IS NULL AND verification_token_expires_at IS NULL) OR (verification_token IS NOT NULL AND verification_token_expires_at IS NOT NULL)",
            name="ck_police_verification_token_expiry_both_null_or_set",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "incidents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("incident_datetime", mssql.DATETIMEOFFSET(), nullable=False),
        sa.Column(
            "severity",
            sa.Enum(
                "REMOTE_WARNING",
                "IN_PERSON_WARNING",
                "CITATION",
                name="incidentseverity",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("description", sa.String(length=2000), nullable=False),
        sa.Column("reference_id", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=True),
        sa.Column("police_id", sa.Integer(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(account_id IS NULL AND police_id IS NOT NULL) OR (account_id IS NOT NULL AND police_id IS NULL)",
            name="refresh_token_owner_check",
        ),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["police_id"], ["police.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_refresh_tokens_account_id"), "refresh_tokens", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_refresh_tokens_police_id"), "refresh_tokens", ["police_id"], unique=False
    )
    op.create_index(
        op.f("ix_refresh_tokens_token_hash"), "refresh_tokens", ["token_hash"], unique=True
    )
    op.create_table(
        "students",
        sa.Column("account_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column(
            "contact_preference",
            sa.Enum("CALL", "TEXT", name="contactpreference", native_enum=False, length=20),
            nullable=True,
        ),
        sa.Column("phone_number", sa.String(length=20), nullable=True),
        sa.Column("last_registered", mssql.DATETIMEOFFSET(), nullable=True),
        sa.Column("residence_id", sa.Integer(), nullable=True),
        sa.Column("residence_chosen_date", mssql.DATETIMEOFFSET(), nullable=True),
        sa.CheckConstraint(
            "(residence_id IS NULL AND residence_chosen_date IS NULL) OR (residence_id IS NOT NULL AND residence_chosen_date IS NOT NULL)",
            name="chk_residence_consistency",
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["residence_id"],
            ["locations.id"],
        ),
        sa.PrimaryKeyConstraint("account_id"),
    )
    op.create_index(op.f("ix_students_account_id"), "students", ["account_id"], unique=False)
    op.create_index(
        "ix_students_phone_number_unique",
        "students",
        ["phone_number"],
        unique=True,
        mssql_where=sa.text("phone_number IS NOT NULL"),
    )
    op.create_table(
        "parties",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("party_datetime", mssql.DATETIMEOFFSET(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("contact_one_id", sa.Integer(), nullable=False),
        sa.Column("contact_two_email", sa.String(length=255), nullable=False),
        sa.Column("contact_two_first_name", sa.String(length=255), nullable=False),
        sa.Column("contact_two_last_name", sa.String(length=255), nullable=False),
        sa.Column("contact_two_phone_number", sa.String(length=20), nullable=False),
        sa.Column(
            "contact_two_contact_preference",
            sa.Enum("CALL", "TEXT", name="contactpreference", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("CONFIRMED", "CANCELLED", name="partystatus", native_enum=False, length=20),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["contact_one_id"], ["students.account_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("parties")
    op.drop_index(
        "ix_students_phone_number_unique",
        table_name="students",
        mssql_where=sa.text("phone_number IS NOT NULL"),
    )
    op.drop_index(op.f("ix_students_account_id"), table_name="students")
    op.drop_table("students")
    op.drop_index(op.f("ix_refresh_tokens_token_hash"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_police_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_account_id"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_table("incidents")
    op.drop_table("police")
    op.drop_index(op.f("ix_locations_google_place_id"), table_name="locations")
    op.drop_index("idx_lat_lng", table_name="locations")
    op.drop_table("locations")
    op.drop_index(op.f("ix_accounts_pid"), table_name="accounts")
    op.drop_index(op.f("ix_accounts_onyen"), table_name="accounts")
    op.drop_index(op.f("ix_accounts_email"), table_name="accounts")
    op.drop_table("accounts")
    # ### end Alembic commands ###
